### ISSUE TITLE
Error with babel

### ISSUE THREAD

**Issue by vbourgeois** [nodefony/nodefony-stage#6]
Hello,

There is an error with babel when building the project:

```
    ERROR in ./src/core.js
    Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/home/vincent/.babelrc" at 0, attempted to resolve relative to "/home/vincent"
        at /home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
        at Array.map (native)
        at Function.normalisePlugins (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
        at OptionManager.mergeOptions (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
        at OptionManager.init (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/home/vincent/git/nodefony-stage/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/home/vincent/git/nodefony-stage/node_modules/babel-loader/lib/index.js:48:20)
        at Object.module.exports (/home/vincent/git/nodefony-stage/node_modules/babel-loader/lib/index.js:163:20)
```

Regards,
Vincent B.

**Comment by ccamensuli** [comment]
Hi vincent ,

Nodefony-stage don't have the dependency  plugin
"transform-object-rest-spread" you have this one on your .babelrc in
"/home/vincent/.babelrc"perhaps for an other project . 
You can try to install this one globally :
https://babeljs.io/docs/plugins/transform-object-rest-spread or delete to
your .babelrc 

Christophe

**Comment by ccamensuli** [comment]
Vincent ,

There is no documentation yet for this library what do you want to use ?

**Comment by vbourgeois** [comment]
Thx it is working, I've never used babel, so I don't know exactly why I have this .babelrc...

I'm from the SmartCC team, working on packaging the lib for our needs.
